sinclude  $(GIZMOSDK)/build/buildflags
sinclude  $(GIZMOSDK)/build/compilerflags
sinclude  $(GIZMOSDK)/build/libraryflags

FILES = cube.o  

TARGET = cube

include $(GIZMOSDK)/build/Makefile.inc

all : 
	make $(TARGET)

