include ../ws/unix/main/compilerflags

all:
	cd encoder ; make $(PLATFORM) 
	cd encoder ; make release
	cd encoder ; make
	cd encoder ; make debug
	cd encoder ; make
	cd evaluators ; make $(PLATFORM) 
	cd evaluators ; make release
	cd evaluators ; make
	cd evaluators ; make debug
	cd evaluators ; make
	cd gizmochat ; make $(PLATFORM) 
	cd gizmochat ; make release
	cd gizmochat ; make
	cd gizmochat ; make debug
	cd gizmochat ; make
	cd helloevent ; make $(PLATFORM) 
	cd helloevent ; make release
	cd helloevent ; make
	cd helloevent ; make debug
	cd helloevent ; make
	cd helloobject ; make $(PLATFORM) 
	cd helloobject ; make release
	cd helloobject ; make
	cd helloobject ; make debug
	cd helloobject ; make
	cd hierarchy ; make $(PLATFORM) 
	cd hierarchy ; make release
	cd hierarchy ; make
	cd hierarchy ; make debug
	cd hierarchy ; make
	cd main ; make $(PLATFORM) 
	cd main ; make release
	cd main ; make
	cd main ; make debug
	cd main ; make
	cd ownership ; make $(PLATFORM) 
	cd ownership ; make release
	cd ownership ; make
	cd ownership ; make debug
	cd ownership ; make
	cd server ; make $(PLATFORM) 
	cd server ; make release
	cd server ; make
	cd server ; make debug
	cd server ; make
	cd subscriptions ; make $(PLATFORM) 
	cd subscriptions ; make release
	cd subscriptions ; make
	cd subscriptions ; make debug
	cd subscriptions ; make
	cd tcp ; make $(PLATFORM) 
	cd tcp ; make release
	cd tcp ; make
	cd tcp ; make debug
	cd tcp ; make
	cd transactions ; make $(PLATFORM) 
	cd transactions ; make release
	cd transactions ; make
	cd transactions ; make debug
	cd transactions ; make

clean:
	cd encoder ; make clean
	cd evaluators ; make clean
	cd gizmochat ; make clean
	cd helloevent ; make clean
	cd helloobject ; make clean
	cd hierarchy ; make clean
	cd main ; make clean
	cd ownership ; make clean
	cd server ; make clean
	cd subscriptions ; make clean
	cd tcp ; make clean
	cd transactions ; make clean

run:


