sinclude  $(GIZMOSDK)/build/buildflags
sinclude  $(GIZMOSDK)/build/compilerflags
sinclude  $(GIZMOSDK)/build/libraryflags

FILES = datagen.o  

TARGET = datagen

include $(GIZMOSDK)/build/Makefile.inc

all : 
	make $(TARGET)

