sinclude  $(GIZMOSDK)/build/buildflags
sinclude  $(GIZMOSDK)/build/compilerflags
sinclude  $(GIZMOSDK)/build/libraryflags

FILES = gzsetenv.o  

TARGET = gzsetenv

include $(GIZMOSDK)/build/Makefile.inc

all : 
	make -f Makefile.gzsetenv $(TARGET)

