include ../ws/unix/main/compilerflags

clean:
	cd billboard ; make clean
	cd skybox ; make clean

	
buildtest:
	cd billboard ; make $(PLATFORM) 
	cd billboard ; make release
	cd billboard ; make
	cd billboard ; make debug
	cd billboard ; make
	cd billboard ; make clean
	cd cube ; make $(PLATFORM) 
	cd cube ; make release
	cd cube ; make
	cd cube ; make debug
	cd cube ; make
	cd cube ; make clean
	cd customNode ; make $(PLATFORM) 
	cd customNode ; make release
	cd customNode ; make
	cd customNode ; make debug
	cd customNode ; make
	cd customNode ; make clean
	cd dbviewer ; make $(PLATFORM) 
	cd dbviewer ; make release
	cd dbviewer ; make
	cd dbviewer ; make debug
	cd dbviewer ; make
	cd dbviewer ; make clean
	cd gzconv ; make $(PLATFORM) 
	cd gzconv ; make release
	cd gzconv ; make
	cd gzconv ; make debug
	cd gzconv ; make
	cd gzconv ; make clean
	cd imagerender ; make $(PLATFORM) 
	cd imagerender ; make release
	cd imagerender ; make
	cd imagerender ; make debug
	cd imagerender ; make
	cd imagerender ; make clean
	cd ir_shader ; make $(PLATFORM) 
	cd ir_shader ; make release
	cd ir_shader ; make
	cd ir_shader ; make debug
	cd ir_shader ; make
	cd ir_shader ; make clean
	cd large ; make $(PLATFORM) 
	cd large ; make release
	cd large ; make
	cd large ; make debug
	cd large ; make
	cd large ; make clean
	cd lod ; make $(PLATFORM) 
	cd lod ; make release
	cd lod ; make
	cd lod ; make debug
	cd lod ; make
	cd lod ; make clean
	cd material ; make $(PLATFORM) 
	cd material ; make release
	cd material ; make
	cd material ; make debug
	cd material ; make
	cd material ; make clean
	cd mirror ; make $(PLATFORM) 
	cd mirror ; make release
	cd mirror ; make
	cd mirror ; make debug
	cd mirror ; make
	cd mirror ; make clean
	cd multipass ; make $(PLATFORM) 
	cd multipass ; make release
	cd multipass ; make
	cd multipass ; make debug
	cd multipass ; make
	cd multipass ; make clean
	cd osxwin ; make $(PLATFORM) 
	cd osxwin ; make release
	cd osxwin ; make
	cd osxwin ; make debug
	cd osxwin ; make
	cd osxwin ; make clean
	cd polytest ; make $(PLATFORM) 
	cd polytest ; make release
	cd polytest ; make; 
	cd polytest ;make debug
	cd polytest ; make
	cd polytest ; make clean
	cd qtwin ; make $(PLATFORM) 
	cd qtwin ; make release
	cd qtwin ; make
	cd qtwin ; make debug
	cd qtwin ; make
	cd qtwin ; make clean
	cd shaders ; make $(PLATFORM) 
	cd shaders ; make release
	cd shaders ; make
	cd shaders ; make debug
	cd shaders ; make
	cd shaders ; make clean
	cd showWindow ; make $(PLATFORM) 
	cd showWindow ; make release
	cd showWindow ; make
	cd showWindow ; make debug
	cd showWindow ; make
	cd showWindow ; make clean
	cd skybox ; make $(PLATFORM) 
	cd skybox ; make release
	cd skybox ; make
	cd skybox ; make debug
	cd skybox ; make
	cd skybox ; make clean
	cd texcube ; make $(PLATFORM) 
	cd texcube ; make release
	cd texcube ; make
	cd texcube ; make debug
	cd texcube ; make
	cd texcube ; make clean
	cd tree ; make $(PLATFORM) 
	cd tree ; make release
	cd tree ; make
	cd tree ; make debug
	cd tree ; make
	cd tree ; make clean
	cd window ; make $(PLATFORM) 
	cd window ; make release
	cd window ; make
	cd window ; make debug
	cd window ; make
	cd window ; make clean


	# All examples were built ok !!!!!!

runtest:
	cd billboard ; make $(PLATFORM) 
	cd billboard ; make release
	cd billboard ; make
	cd billboard ; make run
	cd billboard ; make debug
	cd billboard ; make
	cd billboard ; make run
	cd billboard ; make clean
	cd cube ; make $(PLATFORM) 
	cd cube ; make release
	cd cube ; make
	cd cube ; make run
	cd cube ; make debug
	cd cube ; make
	cd cube ; make run
	cd cube ; make clean
	cd customNode ; make $(PLATFORM) 
	cd customNode ; make release
	cd customNode ; make
	cd customNode ; make run
	cd customNode ; make debug
	cd customNode ; make
	cd customNode ; make run
	cd customNode ; make clean
	cd dbviewer ; make $(PLATFORM) 
	cd dbviewer ; make release
	cd dbviewer ; make
	cd dbviewer ; make run
	cd dbviewer ; make debug
	cd dbviewer ; make
	cd dbviewer ; make run
	cd dbviewer ; make clean
	cd gzconv ; make $(PLATFORM) 
	cd gzconv ; make release
	cd gzconv ; make
	cd gzconv ; make run
	cd gzconv ; make debug
	cd gzconv ; make
	cd gzconv ; make run
	cd gzconv ; make clean
	cd imagerender ; make $(PLATFORM) 
	cd imagerender ; make release
	cd imagerender ; make
	cd imagerender ; make run
	cd imagerender ; make debug
	cd imagerender ; make
	cd imagerender ; make run
	cd imagerender ; make clean
	cd ir_shader ; make $(PLATFORM) 
	cd ir_shader ; make release
	cd ir_shader ; make
	cd ir_shader ; make run
	cd ir_shader ; make debug
	cd ir_shader ; make
	cd ir_shader ; make run
	cd ir_shader ; make clean
	cd large ; make $(PLATFORM) 
	cd large ; make release
	cd large ; make
	cd large ; make run
	cd large ; make debug
	cd large ; make
	cd large ; make run
	cd large ; make clean
	cd lod ; make $(PLATFORM) 
	cd lod ; make release
	cd lod ; make
	cd lod ; make run
	cd lod ; make debug
	cd lod ; make
	cd lod ; make run
	cd lod ; make clean
	cd material ; make $(PLATFORM) 
	cd material ; make release
	cd material ; make
	cd material ; make run
	cd material ; make debug
	cd material ; make
	cd material ; make run
	cd material ; make clean
	cd mirror ; make $(PLATFORM) 
	cd mirror ; make release
	cd mirror ; make
	cd mirror ; make run
	cd mirror ; make debug
	cd mirror ; make
	cd mirror ; make run
	cd mirror ; make clean
	cd multipass ; make $(PLATFORM) 
	cd multipass ; make release
	cd multipass ; make
	cd multipass ; make run
	cd multipass ; make debug
	cd multipass ; make
	cd multipass ; make run
	cd multipass ; make clean
	cd osxwin ; make $(PLATFORM) 
	cd osxwin ; make release
	cd osxwin ; make
	cd osxwin ; make run
	cd osxwin ; make debug
	cd osxwin ; make
	cd osxwin ; make run
	cd osxwin ; make clean
	cd polytest ; make $(PLATFORM) 
	cd polytest ; make release
	cd polytest ; make
	cd polytest ; make run
	cd polytest ; make debug
	cd polytest ; make
	cd polytest ; make run
	cd polytest ; make clean
#	cd qtwin ; make $(PLATFORM) 
#	cd qtwin ; make release
#	cd qtwin ; make
#	cd qtwin ; make run
#	cd qtwin ; make debug
#	cd qtwin ; make
#	cd qtwin ; make run
#	cd qtwin ; make clean
	cd shaders ; make $(PLATFORM) 
	cd shaders ; make release
	cd shaders ; make
	cd shaders ; make run
	cd shaders ; make debug
	cd shaders ; make
	cd shaders ; make run
	cd shaders ; make clean
	cd showWindow ; make $(PLATFORM) 
	cd showWindow ; make release
	cd showWindow ; make
	cd showWindow ; make run
	cd showWindow ; make debug
	cd showWindow ; make
	cd showWindow ; make run
	cd showWindow ; make clean
	cd skybox ; make $(PLATFORM) 
	cd skybox ; make release
	cd skybox ; make
	cd skybox ; make run
	cd skybox ; make debug
	cd skybox ; make
	cd skybox ; make run
	cd skybox ; make clean
	cd texcube ; make $(PLATFORM) 
	cd texcube ; make release
	cd texcube ; make
	cd texcube ; make run
	cd texcube ; make debug
	cd texcube ; make
	cd texcube ; make run
	cd texcube ; make clean
	cd tree ; make $(PLATFORM) 
	cd tree ; make release
	cd tree ; make
	cd tree ; make run
	cd tree ; make debug
	cd tree ; make
	cd tree ; make run
	cd tree ; make clean
	cd window ; make $(PLATFORM) 
	cd window ; make release
	cd window ; make
	cd window ; make run
	cd window ; make debug	
	cd window ; make
	cd window ; make run
	cd window ; make clean

	# All examples were run ok !!!!!!



	

	


	
