sinclude  $(GIZMOSDK)/build/buildflags
sinclude  $(GIZMOSDK)/build/compilerflags
sinclude  $(GIZMOSDK)/build/libraryflags

FILES = moduleinfo.o  

TARGET = moduleinfo

include $(GIZMOSDK)/build/Makefile.inc

all : 
	make $(TARGET)

