sinclude  $(GIZMOSDK)/build/buildflags
sinclude  $(GIZMOSDK)/build/compilerflags
sinclude  $(GIZMOSDK)/build/libraryflags

FILES = billboard.o  

TARGET = billboard

include $(GIZMOSDK)/build/Makefile.inc

all : 
	make $(TARGET)

