sinclude  $(GIZMOSDK)/build/buildflags
sinclude  $(GIZMOSDK)/build/compilerflags
sinclude  $(GIZMOSDK)/build/libraryflags

TARGET = smartpointer

FILES = smart.o  

include $(GIZMOSDK)/build/Makefile.inc
