sinclude  $(GIZMOSDK)/build/buildflags
sinclude  $(GIZMOSDK)/build/compilerflags
sinclude  $(GIZMOSDK)/build/libraryflags

FILES = exceptions.o  

TARGET = exceptions

include $(GIZMOSDK)/build/Makefile.inc

all : 
	make $(TARGET)

