sinclude  $(GIZMOSDK)/build/buildflags
sinclude  $(GIZMOSDK)/build/compilerflags
sinclude  $(GIZMOSDK)/build/libraryflags

FILES = dyndata.o  

TARGET = dyndata

include $(GIZMOSDK)/build/Makefile.inc

all : 
	make $(TARGET)

