sinclude  $(GIZMOSDK)/build/buildflags
sinclude  $(GIZMOSDK)/build/compilerflags
sinclude  $(GIZMOSDK)/build/libraryflags

TARGET = qtwin

FILES = qtwin.o

INCLUDEPATH=-I$(QTDIR)/include

LIBS=-L$(QTDIR)/lib -l$(QTLIB)

include $(GIZMOSDK)/build/Makefile.inc

