sinclude  $(GIZMOSDK)/build/buildflags
sinclude  $(GIZMOSDK)/build/compilerflags
sinclude  $(GIZMOSDK)/build/libraryflags

FILES = messages.o  

TARGET = messages

include $(GIZMOSDK)/build/Makefile.inc

all : 
	make $(TARGET)

