sinclude  $(GIZMOSDK)/build/buildflags
sinclude  $(GIZMOSDK)/build/compilerflags
sinclude  $(GIZMOSDK)/build/libraryflags


FILES = threads.o  

TARGET = threads

include $(GIZMOSDK)/build/Makefile.inc

all : 
	make $(TARGET)
