sinclude  $(GIZMOSDK)/build/buildflags
sinclude  $(GIZMOSDK)/build/compilerflags
sinclude  $(GIZMOSDK)/build/libraryflags

FILES = machid.o  

TARGET = machid

include $(GIZMOSDK)/build/Makefile.inc

all : 
	make $(TARGET)

